using Estore.CoreBusiness.Models;
using Estore.CoreBusiness.PluginInterfaces.DataStore;
using System.Collections.Generic;

namespace Estore.DataStore.HardCoded
{
	public class ProductRepository: IProductRepository
	{
		private List<Product> products;
        public ProductRepository()
        {
			products = new List<Product>
			{
				new Product { Id = 1, Brand = "Lenovo", Name = "ThinkPad", Price = 1139, Description = "Business-grade durability (ThinkPad), ultra-portable (X1 Carbon, X13), touchscreen versatility (Yoga), and more affordable models for everyday use.", ImageLink = "https://www.google.com/imgres?q=thinkpad%20laptop&imgurl=https%3A%2F%2Fi.pcmag.com%2Fimagery%2Froundups%2F01WVjMAdwpsB2gomJXcqpNl-41..v1743518672.jpg&imgrefurl=https%3A%2F%2Fwww.pcmag.com%2Fpicks%2Fthe-best-lenovo-laptops&docid=xZ4tmMQZPloTRM&tbnid=7UuexZOVnN19xM&vet=12ahUKEwizt_OZ-OaNAxVuV6QEHfjoEqcQM3oFCIEBEAA..i&w=1280&h=720&hcb=2&ved=2ahUKEwizt_OZ-OaNAxVuV6QEHfjoEqcQM3oFCIEBEAA" },
				new Product { Id = 2, Brand = "HP (Hewlett-Packard)", Name = "EliteBook ", Price = 2000, Description = "Versatile 2‑in‑1 convertibles (Spectre, Envy), professional business machines (Elite), and gaming rigs (Omen). Known for elegant designs and solid performance", ImageLink = "https://www.google.com/imgres?q=elitebook%20laptop&imgurl=https%3A%2F%2Fwww.laptopsfactory.co.ke%2Fwp-content%2Fuploads%2F2024%2F02%2F54.png&imgrefurl=https%3A%2F%2Fwww.laptopsfactory.co.ke%2Fproduct%2Fhp-elitebook-820-g4-12-5-laptop-intel-core-i5-7300u-8gb-ddr4-256gb-ssd-windows-10-pro-compact-and-powerful-general-purpose-ultrabook%2F&docid=Bp-fawUMXPTBDM&tbnid=ToxQA4AYVknJ3M&vet=12ahUKEwjysaC4-OaNAxVhS_EDHRFYGtUQM3oECBgQAA..i&w=1080&h=1080&hcb=2&ved=2ahUKEwjysaC4-OaNAxVhS_EDHRFYGtUQM3oECBgQAA" },
				new Product { Id = 3, Brand = "Apple (Macintosh)", Name = "MacBook Pro", Price = 1599, Description = "Premium aluminum build, industry-leading performance with M4 chips, outstanding battery life, and tight hardware/software integration—ideal for creatives and professionals", ImageLink = "https://www.google.com/imgres?q=macbook%20pro%20laptop&imgurl=https%3A%2F%2Fwww.apple.com%2Fnewsroom%2Fimages%2Fproduct%2Fmac%2Fstandard%2FApple_16-inch-MacBook-Pro_111319_big.jpg.large.jpg&imgrefurl=https%3A%2F%2Fwww.apple.com%2Fke%2Fnewsroom%2F2019%2F11%2Fapple-introduces-16-inch-macbook-pro-the-worlds-best-pro-notebook%2F&docid=DHve2lQUQHbHwM&tbnid=3B7YyO00PKDUQM&vet=12ahUKEwiIt_LM-OaNAxUGSaQEHZ17C4YQM3oECBsQAA..i&w=816&h=590&hcb=2&ved=2ahUKEwiIt_LM-OaNAxUGSaQEHZ17C4YQM3oECBsQAA" },
				new Product { Id = 4, Brand = "Dell", Name = "XPS", Price = 1149, Description = "Flagship XPS series with sleek aluminum and Gorilla Glass, powerful Intel Ultra chips, OLED displays, and strong build quality—excellent for productivity and light content creation.", ImageLink = "https://www.google.com/imgres?q=xps%20laptop&imgurl=https%3A%2F%2Fwww.ubuy.ke%2Fproductimg%2F%3Fimage%3DaHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNDFsMm8wdFRUeEwuX1NTNDAwXy5qcGc.jpg&imgrefurl=https%3A%2F%2Fwww.ubuy.ke%2Fen%2Fproduct%2F7BPQQJCQU-dell-xps-13-plus-9320-13-4-touchscreen-notebook-full-hd-plus-1920-x-1200-intel-core-i7-12th-gen-i7-1260p-dodeca-core-12-core-intel-evo&docid=gr-hR8Ck_tEcjM&tbnid=OnSxgqZm7ALAkM&vet=12ahUKEwjNvJXf-OaNAxU_UKQEHVwcOlkQM3oECCEQAA..i&w=500&h=500&hcb=2&ved=2ahUKEwjNvJXf-OaNAxU_UKQEHVwcOlkQM3oECCEQAA" },
                new Product { Id = 5, Brand = "Asus", Name = "ROG", Price = 2500, Description = "Offers value-packed ultrabooks (ZenBook, VivoBook), high-end creative/gaming rigs (ProArt, ROG) with strong performance, sleek design, and innovative display options.", ImageLink = "https://www.google.com/imgres?q=Asuslaptop&imgurl=https%3A%2F%2Fvader-prod.s3.amazonaws.com%2F1728413302-1719761072-1711546349-asus-gaming-laptop-66041fbea8391.jpg&imgrefurl=https%3A%2F%2Fregistry.ru.ac.ke%2F%3Fy%3D1112918350120&docid=mkQ57V9LIyneyM&tbnid=P6TCpMmdKlEfzM&vet=12ahUKEwjX0avx-OaNAxVTQfEDHfvIATIQM3oECGgQAA..i&w=1500&h=1500&hcb=2&ved=2ahUKEwjX0avx-OaNAxVTQfEDHfvIATIQM3oECGgQAA" },
                new Product { Id = 6, Brand = "Acer", Name = "Aspire", Price = 600, Description = "Budget-friendly (Chromebooks, Aspire), light and stylish (Swift), and into gaming with Predator and Nitro series—broad range from casual use to gaming.", ImageLink = "https://www.google.com/imgres?q=acer%20laptop&imgurl=https%3A%2F%2Fmicroless.com%2Fcdn%2Fproducts%2Fbd0064c7788fdb6fda05502a6249bf7f-md.jpg&imgrefurl=https%3A%2F%2Fke.microless.com%2Fproduct%2Facer-laptop-black-aspire-3-15-6-core-i5-8gb-ram-a315-01m-blk%2F&docid=T3sy2oy-wZgxhM&tbnid=fyyOEMFDz-H-nM&vet=12ahUKEwiHjMj9-OaNAxVFRaQEHXSyIeQQM3oECHUQAA..i&w=525&h=324&hcb=2&ved=2ahUKEwiHjMj9-OaNAxVFRaQEHXSyIeQQM3oECHUQAA" },
                new Product { Id = 7, Brand = "Razer", Name = "Razer Blade", Price = 3499, Description = "Premium gaming laptops with sleek aluminum chassis, RGB keyboards, top-tier GPUs—favored by gamers and creators who want portability and power.", ImageLink = "https://www.google.com/imgres?q=razer%20laptop&imgurl=https%3A%2F%2Fwww.pcworld.com%2Fwp-content%2Fuploads%2F2025%2F04%2FRazer-Blade-15-1.jpg%3Fquality%3D50%26strip%3Dall&imgrefurl=https%3A%2F%2Fwww.pcworld.com%2Farticle%2F1064746%2Frazer-blade-15-review-2.html&docid=6w0CVfge_EHsBM&tbnid=9DT4zKBkAI-tEM&vet=12ahUKEwiskqOQ-eaNAxWrT6QEHRDECXYQM3oECHAQAA..i&w=4032&h=3024&hcb=2&ved=2ahUKEwiskqOQ-eaNAxWrT6QEHRDECXYQM3oECHAQAA" },
                new Product { Id = 8, Brand = "Microsoft", Name = "Surface Book", Price = 1599, Description = "Premium Windows laptops with clean design, high-res touch displays, light weight—great for office, students, and light creative tasks with excellent build.", ImageLink = "https://www.google.com/imgres?q=surface%20book%20laptop&imgurl=https%3A%2F%2Fmedia.wired.com%2Fphotos%2F5a0c9f1035456e50a57c91d5%2F1%3A1%2Fw_1837%2Ch_1837%2Cc_limit%2Fsurface-FA.jpg&imgrefurl=https%3A%2F%2Fwww.wired.com%2Freview%2Freview-microsoft-surface-book-2%2F&docid=Uh7uREGc-jgG_M&tbnid=RAjnv1dq-6YOeM&vet=12ahUKEwiswZiy-eaNAxXGvicCHRnTLvoQM3oECHoQAA..i&w=1837&h=1837&hcb=2&ved=2ahUKEwiswZiy-eaNAxXGvicCHRnTLvoQM3oECHoQAA" },
                new Product { Id = 9, Brand = "Samsung", Name = "Galaxy Book", Price = 1599, Description = "Lightweight Windows laptops often with AMOLED screens, stylus-ready models—designed for mobile productivity closely integrated with Samsung ecosystem.", ImageLink = "https://www.google.com/imgres?q=galaxy%20book%20laptop&imgurl=https%3A%2F%2Fwww.androidfaithful.com%2Fcontent%2Fimages%2Fsize%2Fw2000%2F2024%2F12%2FGalaxy_Book_5_Pro_360_hero_image.jpg&imgrefurl=https%3A%2F%2Fwww.androidfaithful.com%2Fgalaxy-book5-pro-review%2F&docid=IEpVKt3wJwWOlM&tbnid=mhB3VjhZzAAYHM&vet=12ahUKEwjfpc-9-eaNAxV_bKQEHTo5L6cQM3oECHYQAA..i&w=1920&h=1085&hcb=2&ved=2ahUKEwjfpc-9-eaNAxV_bKQEHTo5L6cQM3oECHYQAA" },
                new Product { Id = 10, Brand = "MSI (Micro-Star International)", Name = "MSI", Price = 3000, Description = "Specialized in high-performance gaming and content creation machines with powerful GPUs, high-refresh screens, optimized cooling for intensive workloads.", ImageLink = "https://www.google.com/imgres?q=MSI%20laptop&imgurl=https%3A%2F%2Fi5.walmartimages.com%2Fseo%2FMSI-GL63-Gaming-Laptop-15-6-Intel-Core-i7-8750H-NVIDIA-GeForce-GTX-1050-8gb-RAM-256gb-SSD-1TB-HDD_3a04f0fc-6fed-4b52-912c-11317e493ad1_1.9e46d617254b76bff5a4cda944922f78.jpeg&imgrefurl=https%3A%2F%2Fwww.ubuy.ke%2Fen%2Fproduct%2FCEVLP5K-msi-gl63-gaming-laptop-15-6-intel-core-i7-8750h-nvidia-geforce-gtx-1050-8gb-ram-256gb-ssd-1tb-hdd&docid=diszL8fe2_RYLM&tbnid=dG6pf3wEnBg8DM&vet=12ahUKEwjZ273U-eaNAxWLSaQEHQhJEYgQM3oECBgQAA..i&w=2880&h=1840&hcb=2&ved=2ahUKEwjZ273U-eaNAxWLSaQEHQhJEYgQM3oECBgQAA" }
            };
            
        }

        public Product GetProduct(int id)
        {
            return products.FirstOrDefault(p => p.Id == id);
        }

        public IEnumerable<Product> GetProducts(string filter)
        {
            if (string.IsNullOrWhiteSpace(filter)) return products;
            
            return products.Where(p => p.Name.Tolower().Contains(filter.ToLower())
        }
    }
}
